
language: java
sudo: false


after_success:
  - bash <(curl -s https://codecov.io/bash)


notifications:
  email:
    recipients:
      - shegay24@mail.ru
    on_success: never # default: change
    on_failure: always # default: always